name: Run regression environment

on:
  workflow_dispatch:
  # schedule:
  #  - cron: 0 1 * * * # run at 1 AM UTC

jobs:
  build_docker_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images with testcases and run regression
        env:
              IMAGE_NAME: ghcr.io/saicharan0112/magic_netgen_ci:alpha
        run: |
          cd $GITHUB_WORKSPACE/regression
          docker build --tag $IMAGE_NAME --no-cache --build-arg key=${{ secrets.MAIL_KEY }} --build-arg emails=${{ secrets.MAIL_LIST }} .