name: Build/Update regression environment

on:
  workflow_dispatch:

jobs:
  build_ci_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the docker image
        env:
              IMAGE_NAME: ghcr.io/saicharan0112/magic_netgen_ci:alpha
        run: |
          cd $GITHUB_WORKSPACE/environment
          docker build . --tag $IMAGE_NAME --no-cache
          docker push $IMAGE_NAME
